name: Double-check PRs

on:
  push:
    branches:
    - main

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test-and-lint:
    uses: ./.github/workflows/testing.yml

  build-docs:
    needs: test-and-lint
    uses: ./.github/workflows/build_docs.yml
