name: Test and lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test-and-lint-code:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: |
          pip install --upgrade hatch
      - name: Test and lint
        run: |
          hatch run dev.py${{ matrix.python-version }}:tests

  test-docs-build:
    needs: test-and-lint-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install hatch
      run: |
        pip install --upgrade hatch

    - name: Build the book
      run: |
        hatch run dev.py3.10:docs

    - name: Keep docs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ./_build/html
        if-no-files-found: error
